from tkinter import *

okno = Tk()

pierwszyRzad = Frame(okno)
drugiRzad = Frame(okno)
trzeciRzad = Frame(okno)
czwartyRzad = Frame(okno)
piatyRzad = Frame(okno)
szostyRzad = Frame(okno)
siodmyRzad = Frame(okno)
osmyRzad = Frame(okno)

pierwszyRzad.pack()
drugiRzad.pack()
trzeciRzad.pack()
czwartyRzad.pack()
piatyRzad.pack()
szostyRzad.pack()
siodmyRzad.pack()
osmyRzad.pack()

#Pierwszy rzad przyciskow
przycisk1 = Button(pierwszyRzad, text="1")
przycisk2 = Button(pierwszyRzad, text="2")
przycisk3 = Button(pierwszyRzad, text="3")
przycisk4 = Button(pierwszyRzad, text="4")
przycisk5 = Button(pierwszyRzad, text="5")
przycisk6 = Button(pierwszyRzad, text="6")
przycisk7 = Button(pierwszyRzad, text="7")
przycisk8 = Button(pierwszyRzad, text="8")
przycisk1.pack(side=LEFT)
przycisk2.pack(side=LEFT)
przycisk3.pack(side=LEFT)
przycisk4.pack(side=LEFT)
przycisk5.pack(side=LEFT)
przycisk6.pack(side=LEFT)
przycisk7.pack(side=LEFT)
przycisk8.pack(side=LEFT)

#Drugi rzad przyciskow
przycisk9 = Button(drugiRzad, text="9")
przycisk10 = Button(drugiRzad, text="10")
przycisk11 = Button(drugiRzad, text="11")
przycisk12 = Button(drugiRzad, text="12")
przycisk13 = Button(drugiRzad, text="13")
przycisk14 = Button(drugiRzad, text="14")
przycisk15 = Button(drugiRzad, text="15")
przycisk16 = Button(drugiRzad, text="16")
przycisk9.pack(side=LEFT)
przycisk10.pack(side=LEFT)
przycisk11.pack(side=LEFT)
przycisk12.pack(side=LEFT)
przycisk13.pack(side=LEFT)
przycisk14.pack(side=LEFT)
przycisk15.pack(side=LEFT)
przycisk16.pack(side=LEFT)

#Trzeci rzad przyciskow
przycisk17 = Button(trzeciRzad, text="17")
przycisk18 = Button(trzeciRzad, text="18")
przycisk19 = Button(trzeciRzad, text="19")
przycisk20 = Button(trzeciRzad, text="20")
przycisk21 = Button(trzeciRzad, text="21")
przycisk22 = Button(trzeciRzad, text="22")
przycisk23 = Button(trzeciRzad, text="23")
przycisk24 = Button(trzeciRzad, text="24")
przycisk17.pack(side=LEFT)
przycisk18.pack(side=LEFT)
przycisk19.pack(side=LEFT)
przycisk20.pack(side=LEFT)
przycisk21.pack(side=LEFT)
przycisk22.pack(side=LEFT)
przycisk23.pack(side=LEFT)
przycisk24.pack(side=LEFT)

#Czwarty rzad przyciskow
przycisk25 = Button(czwartyRzad, text="25")
przycisk26 = Button(czwartyRzad, text="26")
przycisk27 = Button(czwartyRzad, text="27")
przycisk28 = Button(czwartyRzad, text="28")
przycisk29 = Button(czwartyRzad, text="29")
przycisk30 = Button(czwartyRzad, text="30")
przycisk31 = Button(czwartyRzad, text="31")
przycisk32 = Button(czwartyRzad, text="32")
przycisk25.pack(side=LEFT)
przycisk26.pack(side=LEFT)
przycisk27.pack(side=LEFT)
przycisk28.pack(side=LEFT)
przycisk29.pack(side=LEFT)
przycisk30.pack(side=LEFT)
przycisk31.pack(side=LEFT)
przycisk32.pack(side=LEFT)

#Piaty rzad przyciskow
przycisk33 = Button(piatyRzad, text="33")
przycisk34 = Button(piatyRzad, text="34")
przycisk35 = Button(piatyRzad, text="35")
przycisk36 = Button(piatyRzad, text="36")
przycisk37 = Button(piatyRzad, text="37")
przycisk38 = Button(piatyRzad, text="38")
przycisk39 = Button(piatyRzad, text="39")
przycisk40 = Button(piatyRzad, text="40")
przycisk33.pack(side=LEFT)
przycisk34.pack(side=LEFT)
przycisk35.pack(side=LEFT)
przycisk36.pack(side=LEFT)
przycisk37.pack(side=LEFT)
przycisk38.pack(side=LEFT)
przycisk39.pack(side=LEFT)
przycisk40.pack(side=LEFT)

#Szosty rzad przyciskow
przycisk41 = Button(szostyRzad, text="41")
przycisk42 = Button(szostyRzad, text="42")
przycisk43 = Button(szostyRzad, text="43")
przycisk44 = Button(szostyRzad, text="44")
przycisk45 = Button(szostyRzad, text="45")
przycisk46 = Button(szostyRzad, text="46")
przycisk47 = Button(szostyRzad, text="47")
przycisk48 = Button(szostyRzad, text="48")
przycisk41.pack(side=LEFT)
przycisk42.pack(side=LEFT)
przycisk43.pack(side=LEFT)
przycisk44.pack(side=LEFT)
przycisk45.pack(side=LEFT)
przycisk46.pack(side=LEFT)
przycisk47.pack(side=LEFT)
przycisk48.pack(side=LEFT)

#Siodmy rzad przyciskow
przycisk49 = Button(siodmyRzad, text="49")
przycisk50 = Button(siodmyRzad, text="50")
przycisk51 = Button(siodmyRzad, text="51")
przycisk52 = Button(siodmyRzad, text="52")
przycisk53 = Button(siodmyRzad, text="53")
przycisk54 = Button(siodmyRzad, text="54")
przycisk55 = Button(siodmyRzad, text="55")
przycisk56 = Button(siodmyRzad, text="56")
przycisk49.pack(side=LEFT)
przycisk50.pack(side=LEFT)
przycisk51.pack(side=LEFT)
przycisk52.pack(side=LEFT)
przycisk53.pack(side=LEFT)
przycisk54.pack(side=LEFT)
przycisk55.pack(side=LEFT)
przycisk56.pack(side=LEFT)


#Osmy rzad przyciskow
przycisk57 = Button(osmyRzad, text="57")
przycisk58 = Button(osmyRzad, text="58")
przycisk59 = Button(osmyRzad, text="59")
przycisk60 = Button(osmyRzad, text="60")
przycisk61 = Button(osmyRzad, text="61")
przycisk62 = Button(osmyRzad, text="62")
przycisk63 = Button(osmyRzad, text="63")
przycisk64 = Button(osmyRzad, text="63")
przycisk57.pack(side=LEFT)
przycisk58.pack(side=LEFT)
przycisk59.pack(side=LEFT)
przycisk60.pack(side=LEFT)
przycisk61.pack(side=LEFT)
przycisk62.pack(side=LEFT)
przycisk63.pack(side=LEFT)
przycisk64.pack(side=LEFT)

okno.mainloop()
