from tkinter import *

okno = Tk()

pierwszyRzad = Frame(okno)
drugiRzad = Frame(okno)
trzeciRzad = Frame(okno)
czwartyRzad = Frame(okno)
piatyRzad = Frame(okno)
szostyRzad = Frame(okno)
siodmyRzad = Frame(okno)
osmyRzad = Frame(okno)

pierwszyRzad.pack()
drugiRzad.pack()
trzeciRzad.pack()
czwartyRzad.pack()
piatyRzad.pack()
szostyRzad.pack()
siodmyRzad.pack()
osmyRzad.pack()

przycisk = [[0 for x in range(8)]for y in range(8)]

# Pierwszy rzad przyciskow
przycisk[0][0] = Button(pierwszyRzad, text="1")
przycisk[0][1] = Button(pierwszyRzad, text="2")
przycisk[0][2] = Button(pierwszyRzad, text="3")
przycisk[0][3] = Button(pierwszyRzad, text="4")
przycisk[0][4] = Button(pierwszyRzad, text="5")
przycisk[0][5] = Button(pierwszyRzad, text="6")
przycisk[0][6] = Button(pierwszyRzad, text="7")
przycisk[0][7] = Button(pierwszyRzad, text="8")
przycisk[0][0].pack(side=LEFT)
przycisk[0][1].pack(side=LEFT)
przycisk[0][2].pack(side=LEFT)
przycisk[0][3].pack(side=LEFT)
przycisk[0][4].pack(side=LEFT)
przycisk[0][5].pack(side=LEFT)
przycisk[0][6].pack(side=LEFT)
przycisk[0][7].pack(side=LEFT)

# Drugi rzad przyciskow
przycisk[1][0] = Button(drugiRzad, text="9")
przycisk[1][1] = Button(drugiRzad, text="10")
przycisk[1][2] = Button(drugiRzad, text="11")
przycisk[1][3] = Button(drugiRzad, text="12")
przycisk[1][4] = Button(drugiRzad, text="13")
przycisk[1][5] = Button(drugiRzad, text="14")
przycisk[1][6] = Button(drugiRzad, text="15")
przycisk[1][7] = Button(drugiRzad, text="16")
przycisk[1][0].pack(side=LEFT)
przycisk[1][1].pack(side=LEFT)
przycisk[1][2].pack(side=LEFT)
przycisk[1][3].pack(side=LEFT)
przycisk[1][4].pack(side=LEFT)
przycisk[1][5].pack(side=LEFT)
przycisk[1][6].pack(side=LEFT)
przycisk[1][7].pack(side=LEFT)

# Trzeci rzad przyciskow
przycisk[2][0] = Button(trzeciRzad, text="17")
przycisk[2][1] = Button(trzeciRzad, text="18")
przycisk[2][2] = Button(trzeciRzad, text="19")
przycisk[2][3] = Button(trzeciRzad, text="20")
przycisk[2][4] = Button(trzeciRzad, text="21")
przycisk[2][5] = Button(trzeciRzad, text="22")
przycisk[2][6] = Button(trzeciRzad, text="23")
przycisk[2][7] = Button(trzeciRzad, text="24")
przycisk[2][0].pack(side=LEFT)
przycisk[2][1].pack(side=LEFT)
przycisk[2][2].pack(side=LEFT)
przycisk[2][3].pack(side=LEFT)
przycisk[2][4].pack(side=LEFT)
przycisk[2][5].pack(side=LEFT)
przycisk[2][6].pack(side=LEFT)
przycisk[2][7].pack(side=LEFT)

# Czwarty rzad przyciskow
przycisk[3][0] = Button(czwartyRzad, text="25")
przycisk[3][1] = Button(czwartyRzad, text="26")
przycisk[3][2] = Button(czwartyRzad, text="27")
przycisk[3][3] = Button(czwartyRzad, text="28")
przycisk[3][4] = Button(czwartyRzad, text="29")
przycisk[3][5] = Button(czwartyRzad, text="30")
przycisk[3][6] = Button(czwartyRzad, text="31")
przycisk[3][7] = Button(czwartyRzad, text="32")
przycisk[3][0].pack(side=LEFT)
przycisk[3][1].pack(side=LEFT)
przycisk[3][2].pack(side=LEFT)
przycisk[3][3].pack(side=LEFT)
przycisk[3][4].pack(side=LEFT)
przycisk[3][5].pack(side=LEFT)
przycisk[3][6].pack(side=LEFT)
przycisk[3][7].pack(side=LEFT)

# Piaty rzad przyciskow
przycisk[4][0] = Button(piatyRzad, text="33")
przycisk[4][1] = Button(piatyRzad, text="34")
przycisk[4][2] = Button(piatyRzad, text="35")
przycisk[4][3] = Button(piatyRzad, text="36")
przycisk[4][4] = Button(piatyRzad, text="37")
przycisk[4][5] = Button(piatyRzad, text="38")
przycisk[4][6] = Button(piatyRzad, text="39")
przycisk[4][7] = Button(piatyRzad, text="40")
przycisk[4][0].pack(side=LEFT)
przycisk[4][1].pack(side=LEFT)
przycisk[4][2].pack(side=LEFT)
przycisk[4][3].pack(side=LEFT)
przycisk[4][4].pack(side=LEFT)
przycisk[4][5].pack(side=LEFT)
przycisk[4][6].pack(side=LEFT)
przycisk[4][7].pack(side=LEFT)

# Szosty rzad przyciskow
przycisk[5][0] = Button(szostyRzad, text="41")
przycisk[5][1] = Button(szostyRzad, text="42")
przycisk[5][2] = Button(szostyRzad, text="43")
przycisk[5][3] = Button(szostyRzad, text="44")
przycisk[5][4] = Button(szostyRzad, text="45")
przycisk[5][5] = Button(szostyRzad, text="46")
przycisk[5][6] = Button(szostyRzad, text="47")
przycisk[5][7] = Button(szostyRzad, text="48")
przycisk[5][0].pack(side=LEFT)
przycisk[5][1].pack(side=LEFT)
przycisk[5][2].pack(side=LEFT)
przycisk[5][3].pack(side=LEFT)
przycisk[5][4].pack(side=LEFT)
przycisk[5][5].pack(side=LEFT)
przycisk[5][6].pack(side=LEFT)
przycisk[5][7].pack(side=LEFT)

# Siodmy rzad przyciskow
przycisk[6][0] = Button(siodmyRzad, text="49")
przycisk[6][1] = Button(siodmyRzad, text="50")
przycisk[6][2] = Button(siodmyRzad, text="51")
przycisk[6][3] = Button(siodmyRzad, text="52")
przycisk[6][4] = Button(siodmyRzad, text="53")
przycisk[6][5] = Button(siodmyRzad, text="54")
przycisk[6][6] = Button(siodmyRzad, text="55")
przycisk[6][7] = Button(siodmyRzad, text="56")
przycisk[6][0].pack(side=LEFT)
przycisk[6][1].pack(side=LEFT)
przycisk[6][2].pack(side=LEFT)
przycisk[6][3].pack(side=LEFT)
przycisk[6][4].pack(side=LEFT)
przycisk[6][5].pack(side=LEFT)
przycisk[6][6].pack(side=LEFT)
przycisk[6][7].pack(side=LEFT)


# Osmy rzad przyciskow
przycisk[7][0] = Button(osmyRzad, text="57")
przycisk[7][1] = Button(osmyRzad, text="58")
przycisk[7][2] = Button(osmyRzad, text="59")
przycisk[7][3] = Button(osmyRzad, text="60")
przycisk[7][4] = Button(osmyRzad, text="61")
przycisk[7][5] = Button(osmyRzad, text="62")
przycisk[7][6] = Button(osmyRzad, text="63")
przycisk[7][7] = Button(osmyRzad, text="63")
przycisk[7][0].pack(side=LEFT)
przycisk[7][1].pack(side=LEFT)
przycisk[7][2].pack(side=LEFT)
przycisk[7][3].pack(side=LEFT)
przycisk[7][4].pack(side=LEFT)
przycisk[7][5].pack(side=LEFT)
przycisk[7][6].pack(side=LEFT)
przycisk[7][7].pack(side=LEFT)

okno.mainloop()
